image:
  file: .gitpod.dockerfile
vscode:
  extensions:
    - pivotal.vscode-spring-boot@1.25.0:377fW9/qsGxfooPeAvagWg==
    - gabrielbb.vscode-lombok@1.0.0:48tiO1CQwrunMwzQNMVDbg==
    - pivotal.vscode-boot-dev-pack@0.0.9:0G6FMi7mZebwkjjmMnenyw==